apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: mywebapp
    tier: frontend
    student-name: haile-adugna
    student-id: ugr7191
  annotations:
    author: haile-adugna-ugr7191
    submitted-by: haile-adugna-ugr7191
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebapp
      tier: frontend
  template:
    metadata:
      labels:
        app: mywebapp
        tier: frontend
    spec:
      containers:
      - name: mycontainer
        image: devopsjourney1/mywebapp
        ports:
        - containerPort: 80

